package com.bingqiong.bq.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

    public static void mapping(ActiveRecordPlugin arp) {
        arp.addMapping("t_article", "id", Article.class);
        arp.addMapping("t_article_stat", ArticleStat.class);
        arp.addMapping("t_article_type", "id", ArticleType.class);
        arp.addMapping("t_banner", "id", Banner.class);
        arp.addMapping("t_category", "id", Category.class);
        arp.addMapping("t_category_stat", CategoryStat.class);
        arp.addMapping("t_comment", "id", Comment.class);
        arp.addMapping("t_comment_stat", CommentStat.class);
        arp.addMapping("t_user_collection", "id", UserCollection.class);
        arp.addMapping("t_user_follow", "id", UserFollow.class);

        arp.addMapping("t_sensitive", "id", Sensitive.class);
        arp.addMapping("t_card", "uid", Card.class);
        arp.addMapping("t_app_version", "id", AppVersion.class);
        arp.addMapping("t_feedback", "id", FeedBack.class);
    }
}

